spring.application.name=hotel-app
spring.webflux.base-path=/app-hotel
server.port=9001
spring.r2dbc.url=r2dbc:mysql://root:mypassword@localhost/hotel_db
spring.r2dbc.username=root
spring.r2dbc.password=your_password
spring.main.web-application-type=reactive
