spring.application.name=hotel-app
spring.webflux.base-path=/app-hotel
server.port=9001
spring.r2dbc.url=r2dbc:mysql://root:mypassword@localhost/hotel_db
spring.main.web-application-type=reactive
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:DML.sql

api.internal.nationalize.url=https://api.nationalize.io/